//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 06:15:57 PM WET 
//


package generated;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pub_title"/>
 *         &lt;element ref="{}pub_authors"/>
 *         &lt;element ref="{}pub_date"/>
 *         &lt;element ref="{}pub_conference"/>
 *         &lt;element ref="{}pub_journal"/>
 *         &lt;element ref="{}pub_volume"/>
 *         &lt;element ref="{}pub_issue"/>
 *         &lt;element ref="{}pub_pages"/>
 *         &lt;element ref="{}pub_publisher"/>
 *         &lt;element ref="{}pub_description"/>
 *         &lt;element ref="{}pub_scholar_articles"/>
 *         &lt;element ref="{}n_citations"/>
 *         &lt;element ref="{}list_citations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pubTitle",
    "pubAuthors",
    "pubDate",
    "pubConference",
    "pubJournal",
    "pubVolume",
    "pubIssue",
    "pubPages",
    "pubPublisher",
    "pubDescription",
    "pubScholarArticles",
    "nCitations",
    "listCitations"
})
@XmlRootElement(name = "publication")
public class Publication {

    @XmlElement(name = "pub_title", required = true)
    protected String pubTitle;
    @XmlElement(name = "pub_authors", required = true)
    protected String pubAuthors;
    @XmlElement(name = "pub_date", required = true)
    protected String pubDate;
    @XmlElement(name = "pub_conference", required = true)
    protected String pubConference;
    @XmlElement(name = "pub_journal", required = true)
    protected String pubJournal;
    @XmlElement(name = "pub_volume", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pubVolume;
    @XmlElement(name = "pub_issue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pubIssue;
    @XmlElement(name = "pub_pages", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pubPages;
    @XmlElement(name = "pub_publisher", required = true)
    protected String pubPublisher;
    @XmlElement(name = "pub_description", required = true)
    protected String pubDescription;
    @XmlElement(name = "pub_scholar_articles", required = true)
    protected String pubScholarArticles;
    @XmlElement(name = "n_citations", required = true)
    protected BigInteger nCitations;
    @XmlElement(name = "list_citations", required = true)
    protected ListCitations listCitations;

    /**
     * Gets the value of the pubTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubTitle() {
        return pubTitle;
    }

    /**
     * Sets the value of the pubTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubTitle(String value) {
        this.pubTitle = value;
    }

    /**
     * Gets the value of the pubAuthors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubAuthors() {
        return pubAuthors;
    }

    /**
     * Sets the value of the pubAuthors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubAuthors(String value) {
        this.pubAuthors = value;
    }

    /**
     * Gets the value of the pubDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * Sets the value of the pubDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubDate(String value) {
        this.pubDate = value;
    }

    /**
     * Gets the value of the pubConference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubConference() {
        return pubConference;
    }

    /**
     * Sets the value of the pubConference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubConference(String value) {
        this.pubConference = value;
    }

    /**
     * Gets the value of the pubJournal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubJournal() {
        return pubJournal;
    }

    /**
     * Sets the value of the pubJournal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubJournal(String value) {
        this.pubJournal = value;
    }

    /**
     * Gets the value of the pubVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubVolume() {
        return pubVolume;
    }

    /**
     * Sets the value of the pubVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubVolume(String value) {
        this.pubVolume = value;
    }

    /**
     * Gets the value of the pubIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubIssue() {
        return pubIssue;
    }

    /**
     * Sets the value of the pubIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubIssue(String value) {
        this.pubIssue = value;
    }

    /**
     * Gets the value of the pubPages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubPages() {
        return pubPages;
    }

    /**
     * Sets the value of the pubPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubPages(String value) {
        this.pubPages = value;
    }

    /**
     * Gets the value of the pubPublisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubPublisher() {
        return pubPublisher;
    }

    /**
     * Sets the value of the pubPublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubPublisher(String value) {
        this.pubPublisher = value;
    }

    /**
     * Gets the value of the pubDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubDescription() {
        return pubDescription;
    }

    /**
     * Sets the value of the pubDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubDescription(String value) {
        this.pubDescription = value;
    }

    /**
     * Gets the value of the pubScholarArticles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubScholarArticles() {
        return pubScholarArticles;
    }

    /**
     * Sets the value of the pubScholarArticles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubScholarArticles(String value) {
        this.pubScholarArticles = value;
    }

    /**
     * Gets the value of the nCitations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCitations() {
        return nCitations;
    }

    /**
     * Sets the value of the nCitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCitations(BigInteger value) {
        this.nCitations = value;
    }

    /**
     * Gets the value of the listCitations property.
     * 
     * @return
     *     possible object is
     *     {@link ListCitations }
     *     
     */
    public ListCitations getListCitations() {
        return listCitations;
    }

    /**
     * Sets the value of the listCitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListCitations }
     *     
     */
    public void setListCitations(ListCitations value) {
        this.listCitations = value;
    }

}
