
package artifact;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JournalsWeb", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JournalsWeb {


    /**
     * 
     * @return
     *     returns java.util.List<artifact.JournalDAO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllJournals", targetNamespace = "http://ws/", className = "artifact.GetAllJournals")
    @ResponseWrapper(localName = "getAllJournalsResponse", targetNamespace = "http://ws/", className = "artifact.GetAllJournalsResponse")
    public List<JournalDAO> getAllJournals();

    /**
     * 
     * @param arg0
     * @return
     *     returns artifact.JournalDAO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoFromJournal", targetNamespace = "http://ws/", className = "artifact.GetInfoFromJournal")
    @ResponseWrapper(localName = "getInfoFromJournalResponse", targetNamespace = "http://ws/", className = "artifact.GetInfoFromJournalResponse")
    public JournalDAO getInfoFromJournal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<artifact.JournalDAO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderedJournals", targetNamespace = "http://ws/", className = "artifact.GetOrderedJournals")
    @ResponseWrapper(localName = "getOrderedJournalsResponse", targetNamespace = "http://ws/", className = "artifact.GetOrderedJournalsResponse")
    public List<JournalDAO> getOrderedJournals(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTitles", targetNamespace = "http://ws/", className = "artifact.GetTitles")
    @ResponseWrapper(localName = "getTitlesResponse", targetNamespace = "http://ws/", className = "artifact.GetTitlesResponse")
    public List<String> getTitles();

}
