//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 06:15:57 PM WET 
//


package generated;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cit_text"/>
 *         &lt;element ref="{}cit_date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "citText",
    "citDate"
})
@XmlRootElement(name = "citation")
public class Citation {

    @XmlElement(name = "cit_text", required = true)
    protected String citText;
    @XmlElement(name = "cit_date", required = true)
    protected BigInteger citDate;

    /**
     * Gets the value of the citText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitText() {
        return citText;
    }

    /**
     * Sets the value of the citText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitText(String value) {
        this.citText = value;
    }

    /**
     * Gets the value of the citDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCitDate() {
        return citDate;
    }

    /**
     * Sets the value of the citDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCitDate(BigInteger value) {
        this.citDate = value;
    }

}
